### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [lei900/daily-mind-rails-backend#98]
※ 確認後closeしてください

## サービスレビュー

* ストレスなどで悩まされてる方も多いので、いいサービスだと思いました。
* UIやデザインも整っていていいですね。
* クイズと記録の関連性が薄いので、動線としてクイズをやった方が記録をしたくなるような動線を作られるとよいかなと思います。
* 文字が多いように見えるので、イラストや文字サイズや画像などで調整して自然と読めるくらいの文字分量にされるとよいかなと思いました。

## コードレビュー

* すいません、フロントが得意ではないのでバックエンドだけ

https://github.com/lei900/daily-mind-rails-backend/blob/585a457c6764a17fbd106d28f54d289957a74342/app/controllers/api/v1/choices_controller.rb#L5

```
これおそらくwhereではなくfind_byで1レコードのみ取得できるのかなと思いました。

https://github.com/lei900/daily-mind-rails-backend/blob/426f2d2f294deb266928c08f11fecd53d9276411/app/controllers/api/v1/entries_controller.rb#L25

この処理が少しまわりくどいようにも見えたので、communityやdistortionsではなくcommunity_entryやentry_distortionsで渡して上げるとaccepts_nested_attributes_forでそのまま保存出来るかなと思います。

* こちら以外は気になるところはありませんでした。コードやテストもきれいに書けていますし、READMEも見やすいので就活も問題なくいけるかなと思いました。

**Comment by lei900** [comment]
ひさじゅさん、フィードバックありがとうございます！嬉しいです！
お体をお大事になさってください！
